// FoodShop.Ui/src/components/layout/Header.jsx
import React, { Component } from 'react';

class Header extends Component {
  constructor() {
    super();
  }
  render() {
    const { backgroundUrl, title, subtitle } = this.props;
    let { className } = this.props;
    if(!className) {
      className = '';
    }
    return (
      <header
        style={{ 'backgroundImage': `url(${backgroundUrl})` }}
        className={className}
        role="banner"
      >
        <div className="middle overlay">
          <span className="intro-text-small">{subtitle}</span>
          <h1 className="cursive-font">{title}</h1>
        </div>
      </header>
    );
  }
}

export default Header;

// Client/src/app/components/shared/header.component.ts
import { Component, Input, OnInit } from '@angular/core';


@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: [ './header.component.scss' ]
})
export class HeaderComponent implements  OnInit {

  @Input('background-image') backgroundImage: string;
  @Input() big: boolean;
  @Input() subtitle: string;
  @Input() title: string;

  className: string;

  ngOnInit(): void {
    if (!this.backgroundImage) {
      this.backgroundImage = 'http://res.cloudinary.com/dum4mjc9q/image/upload/v1487340138/fon1_gex8nh.jpg';
    }
    if (!this.big) {
      this.className = 'cut';
    }
  }
}

<header [ngClass]="className" [ngStyle]="{'background-image': 'url(' + backgroundImage + ')'}">
  <div class="middle overlay">
    <span class="intro-text-small">{{subtitle}}</span>
    <h1 class="cursive-font">{{title}}</h1>
  </div>
</header>
